### ISSUE TITLE
scheduler caught exception: undefined method `content' for nil:NilClass

### ISSUE THREAD

**Issue by AndrejScak** [acockburn/hadashboard#12]
Hi!
I have another error regarding News widget. However, RSS feeds on Example dashboard are working but I cannot add new one. If I add new widget, the RSS feeds are not displayed. It is very strange that if I put empty variable $news_feeds {} in ha_conf.rb file the Traffic and News RSS feeds are still displayed! It looks like URLs are saved elsewhere.

Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop

scheduler caught exception:
undefined method `content' for nil:NilClass
/home/pi/hadashboard/jobs/news.rb:38:in`rescue in block (2 levels) in latest_headlines'
/home/pi/hadashboard/jobs/news.rb:35:in `block (2 levels) in latest_headlines'
/home/pi/hadashboard/jobs/news.rb:33:in`each'
/home/pi/hadashboard/jobs/news.rb:33:in `block in latest_headlines'
/usr/lib/ruby/2.1.0/open-uri.rb:153:in`open_uri'
/usr/lib/ruby/2.1.0/open-uri.rb:704:in `open'
/usr/lib/ruby/2.1.0/open-uri.rb:34:in`open'
/home/pi/hadashboard/jobs/news.rb:31:in `latest_headlines'
/home/pi/hadashboard/jobs/news.rb:66:in`block (2 levels) in <top (required)>'
/home/pi/hadashboard/jobs/news.rb:65:in `each'
/home/pi/hadashboard/jobs/news.rb:65:in`block in <top (required)>'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in`trigger_block'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in`call'
/var/lib/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

**Comment by AndrejScak** [comment]
I solved the issue. The reason was bad url links to RSS.
