### ISSUE TITLE
Error when starting dashing

### ISSUE THREAD

**Issue by 9arriflex9** [acockburn/hadashboard#38]
Hello, I follow the tutorial and i'm running into this issue when trying to start Dashing,
```
$ dashing start
bundler: failed to load command: thin (/usr/local/bin/thin)
Errno::ENOENT: No such file or directory - config.ru
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `read'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `load'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'
```
I tryed googling the issue there is some solution for dashing but i can't seem to make it work

**Comment by acockburn** [comment]
Try installing node:

```bash
$ sudo apt-get install node
```

**Comment by ghost** [comment]
node is already installed

```
[arriflex@Floppy hadashboard]$ sudo yum install nodejs
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.globo.tech
 * epel: ca.mirror.babylon.network
 * extras: centos.mirror.iweb.ca
 * ius: ius.mirror.constant.com
 * nux-dextop: li.nux.ro
 * updates: mirror2.evolution-host.com
Package 1:nodejs-6.9.1-4.el7.x86_64 already installed and latest version
Nothing to do
```

**Comment by acockburn** [comment]
Check you have thin installed:

```bash
$ sudo gem install thin
```

**Comment by ghost** [comment]
sadly yes

```
[arriflex@Floppy hadashboard]$ sudo gem install thin
[sudo] password for arriflex: 
Fetching: thin-1.7.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed thin-1.7.0
Parsing documentation for thin-1.7.0
Installing ri documentation for thin-1.7.0
1 gem installed
[arriflex@Floppy hadashboard]$ dashing start
bundler: failed to load command: thin (/usr/local/bin/thin)
NameError: uninitialized constant Rufus
  /home/arriflex/.gem/ruby/gems/dashing-1.3.7/lib/dashing/app.rb:11:in `<top (required)>'
  /home/arriflex/.gem/ruby/gems/dashing-1.3.7/lib/dashing.rb:3:in `require'
  /home/arriflex/.gem/ruby/gems/dashing-1.3.7/lib/dashing.rb:3:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /usr/local/share/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/share/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_confi
g'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'
```

**Comment by acockburn** [comment]
That's a different error, sop progress.

Did you successfully run the bundle command? Also, what platform are you on?

**Comment by ghost** [comment]
Hello i'm using CentOS Linux release 7.2.1511 (Core)

and yes i did ran bundle here is the output
```
Using backports 3.6.8
Using bcrypt 3.1.11
Using coffee-script-source 1.11.1
Using execjs 2.0.2
Using daemons 1.2.4
Using rack 1.5.5
Using thread_safe 0.3.5
Using sass 3.2.19
Using tilt 1.4.1
Using multi_json 1.12.1
Using hike 1.2.3
Using eventmachine 1.2.1
Using thor 0.19.4
Using fastercsv 1.5.5
Using json 1.8.3
Using json_pure 1.8.3
Using stringex 1.5.1
Using uuidtools 2.1.5
Using htmlentities 4.3.4
Using mime-types 1.25.1
Using mini_portile2 2.1.0
Using bundler 1.13.6
Using dm-core 1.2.1
Using data_objects 0.10.17
Using bcrypt-ruby 3.1.5
Using coffee-script 2.2.0
Using rack-protection 1.5.3
Using rack-test 0.6.3
Using tzinfo 1.2.2
Using sprockets 2.10.2
Using thin 1.6.4
Using rest-client 1.6.9
Using nokogiri 1.6.8.1
Using dm-aggregates 1.2.0
Using dm-constraints 1.2.0
Using dm-migrations 1.2.0
Using dm-serializer 1.2.2
Using dm-timestamps 1.2.0
Using dm-transactions 1.2.0
Using dm-validations 1.2.0
Using dm-do-adapter 1.2.0
Using do_sqlite3 0.10.17
Using dm-types 1.2.2
Using sinatra 1.4.7
Using rufus-scheduler 2.0.24
Using unirest 1.1.2
Using dm-sqlite-adapter 1.2.0
Using data_mapper 1.2.0
Using sinatra-contrib 1.4.7
Using dashing 1.3.7
Bundle complete! 8 Gemfile dependencies, 51 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by acockburn** [comment]
Looks like the Rufus Scheduler isn't installed - may be a difference in the bundling between CentOS and other OSes.

Try:

```bash
$ gem install rufus-scheduler
```

**Comment by ghost** [comment]
Same result

```
[arriflex@Floppy hadashboard]$ gem install rufus-scheduler
Fetching: rufus-scheduler-3.3.1.gem (100%)
Successfully installed rufus-scheduler-3.3.1
Parsing documentation for rufus-scheduler-3.3.1
Installing ri documentation for rufus-scheduler-3.3.1
1 gem installed
[arriflex@Floppy hadashboard]$ dashing start
bundler: failed to load command: thin (/usr/local/bin/thin)
NameError: uninitialized constant Rufus
  /home/arriflex/.gem/ruby/gems/dashing-1.3.7/lib/dashing/app.rb:11:in `<top (required)>'
  /home/arriflex/.gem/ruby/gems/dashing-1.3.7/lib/dashing.rb:3:in `require'
  /home/arriflex/.gem/ruby/gems/dashing-1.3.7/lib/dashing.rb:3:in `<top (required)>'
  config.ru:1:in `require'
  config.ru:1:in `block in <main>'
  /usr/local/share/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/share/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_confi
g'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
  /home/arriflex/.gem/ruby/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>'
```

**Comment by keatontaylor** [comment]
I am receiving a similar error when attempting to use the hadashboard docker build.

**Comment by ikrowni** [comment]
same issue here dont know what to do or where to go from here

**Comment by acockburn** [comment]
Suggest you install dashboard v2 which is in beta.

**Comment by peteargles** [comment]
I was getting this error because I was running "dashing start" from "/home/[me]/hadashboard/lib" were i left off the installation instructions. 
All I needed to do to resolve for me was "cd .." to go up a level and run the same command.
